### ISSUE TITLE
Update flatpickr version

### ISSUE THREAD

**Issue by JuanGaVS** [zokioki/flatpickr-rails#11]
Hello,

first of all, thanks  for this gem, It has helped me a lot.

I noticed the current flatpickr version is higher than the gem version, Do you have planned to update the flatpickr version? 

Regards

**Comment by zokioki** [comment]
Hello! Updated the gem with the latest flatpickr assets. You can find it in [v4.6.6.0](https://github.com/zokioki/flatpickr-rails/releases/tag/v4.6.6.0).
