### ISSUE TITLE
Update to v4.5.7 to v4.6.3

### ISSUE THREAD

**Issue by dewey** [zokioki/flatpickr-rails#7]
Hey Zoran,

thank you for the gem! I was just wondering if this is still maintained and if there'll be a bump to the latest version (https://github.com/flatpickr/flatpickr/releases) or not. I haven't looked into how much work it would be to do it myself + submit PR yet.

Thank you!

**Comment by zokioki** [comment]
Hi Philipp! Thanks for bringing up the issue, just published a release for the latest flatpickr version, it's available as [v4.6.3.1](https://github.com/zokioki/flatpickr-rails/releases/tag/v4.6.3.1).

**Comment by dewey** [comment]
@zokioki I did not expect this to be done so quickly, thanks a lot!
